server:
  port: 8100 # dev, prod; rsc, func, etc; type; num;

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:3489@localhost:8210/eureka/


services:
  post:
    url: http://resource-post
  board:
    url: http://resource-board
  comment:
    url: http://resouce-comment
  profile:
    url: http://resource-profile